cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

install:
    - "git config core.symlinks true"
    - "git reset --hard"
    - "%PYTHON%\\python.exe -m pip install -r test-requirements.txt"
    - "C:\\Python27\\python.exe -m pip install typing"
    - "git submodule update --init typeshed"
    - "cd typeshed && git config core.symlinks true && git reset --hard && cd .."
    - "%PYTHON%\\python.exe -m pip install ."

build: off

test_script:
    # lint and mypy self check run in Travis
    - "%PYTHON%\\python.exe -m pytest -k \"not (PythonEvaluationSuite and python2)\""

skip_commits:
  files:
    - docs/**/*
    - '**/*.rst'
    - '**/*.md'
    - .gitignore
    - .travis.yml
    - CREDITS
    - LICENSE

skip_branch_with_pr: true
